# Generated by Django 3.1.4 on 2021-01-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Author',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
