# Generated by Django 3.1.5 on 2021-01-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Image',
            field=models.ImageField(default=0, upload_to=None),
            preserve_default=False,
        ),
    ]
