# Generated by Django 3.1.5 on 2021-01-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Image',
            field=models.CharField(max_length=200),
        ),
    ]
