# Generated by Django 3.1.4 on 2021-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210116_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=200)),
                ('ProjectText', models.CharField(max_length=10000)),
                ('Images', models.CharField(max_length=200)),
            ],
        ),
    ]
